### PR TITLE
Changed nginx template to implement changes suggested by NextCloud 14 release notes

### PR DESCRIPTION
**Pull request by belidzs**
The implemented changes were suggested by the [release notes](https://docs.nextcloud.com/server/14/admin_manual/release_notes.html) of NextCloud 14

For background compatibility I used Jinja `if` statements to only include these changes when `nextcloud_version_14_or_higher` is set to `true`. 

Since new installs will probably go with the newest version anyway, I've set its default value to `true`.

However it would be a lot more elegant if the value of this variable would be calculated based on other `nextcloud_version_...` variables.

### CODE REVIEW

**Comment by aalaesar** [comment]
Hi again @belidzs 
Thank you for the contribution

I was also privately working on this one but I wanted to find it "automatically" in order to keep the version selection system not more complicated [than it is already](https://github.com/aalaesar/install_nextcloud#repository-naming-rules).
While testing, I concluded that releases channels  and also the "special" type are not relevants to find if the version is newer than 13
Then I made this truth table  with true conditions. _imply each time, "the variable is defined and ..."_

|OR|latest|major|full|
|---|---|---|---|
|-|yes and (**major** is _null_) |>13\|master|split(".")[0] >13|

I can implement this condition as a private boolean instead of the new variable on you PR _if you allow me_.

Regards, Aal.

**Comment by belidzs** [comment]
hi @aalaesar! As you can see from the commit history I tried to reverse engineer the version selection system to make this work automatically but I eventually decided against it as many edge cases would have to be handled (like nightly builds after NC14 was released, etc) and it was too much work for me at the moment.

So I really don't mind if you pick up from here either in my repo or in yours. It's totally up to you :) I've granted the neccessary write permission already. 

Thanks for your great work on this!

**Comment by aalaesar** [comment]
hi @belidzs,
What were the edge cases you were thinking about ? (may spare me some time 😄  )

With the truth table the only edge case I can think of (for now) is when the user provides an **offline** zip/tar.gz package
but this could be mitigated by making `nextcloud_version_major` mandatory _in this case_

(also updated the truth table for the daily channel)

**Comment by belidzs** [comment]
To be honest the rule system for selecting versions was a bit hard to understand to me and this is why I stopped "reverse engineering" it.

For example I wasn't sure how illegal combinations were handled or what to do when the `daily` or `special` variables are defined. Now I start to understand but I still feel like you are better suited for this job.

**Comment by aalaesar** [comment]
> To be honest the rule system for selecting versions was a bit hard to understand to me and this is why I stopped "reverse engineering" it.

You're right, the parameters and how they work are poorly explained. I initially tried a text/table only ReadMe but It will be much easier to understand with some graphic representation. 

> For example I wasn't sure how illegal combinations were handled or what to do when the `daily` or `special` variables are defined. Now I start to understand but I still feel like you are better suited for this job.

the "heart" of the "link computing system" is in  [vars/main.yml](https://github.com/aalaesar/install_nextcloud/blob/master/vars/main.yml)
It contain one dict with 4 keys. each one representing some kind of jinja2 regex-like for the archive name.

Then in [tasks/nc_download](https://github.com/aalaesar/install_nextcloud/blob/master/tasks/nc_download.yml#L10)
A block a 2 tasks emulate an `If,  then,  else` condition  In case the user choosed _latest_ ,because the file name **is** `latest` in this case.

I'll drawn a finite state machine to explain it in the readme. It may be more understandable.

Regards,
Aal

**Comment by aalaesar** [comment]
hi @belidzs 
I've made [this diagram](https://raw.githubusercontent.com/aalaesar/install_nextcloud/update/readme/files/nextcloud_choosing_version.png) in order to describe how nextcloud names its archives
do you think it make the parameters clearer ?
their is still some typos but the logic is here.

any suggestion is welcome
Regards,
Aal.

**Comment by aalaesar** [comment]
hi @belidzs 
whould you like to review the 3 last commits ?
two brains are better than one :smile:

**Comment by aalaesar** [comment]
Ok.
no pb.
thank you for the feed back. 😃 
Regards.
Aal.

**Pull request merged**
