### PR TITLE
become_user requires become:yes

### PR DESCRIPTION
**Pull request by mihailstoynov**
This was fixed everywhere

I don't understand why `become: yes` is not added at all the places. Am I missing something?

### CODE REVIEW

**Comment by aalaesar** [comment]
Depends on your ansible version.
Back when I built the role,
I had a lot of trouble for running occ commands with the correct user.
for some reason it run the command line with the root user instead of www-data or whatever is its name
Had to troubleshoot and finally get something working without the `become: yes`
I'll do more test with 2.4 & 2.5 ansible versions to see if to work correctly now

**Comment by aalaesar** [comment]
By the way.
is this PR make obsolete the 2 other ones ?
#52 & #53

**Comment by mihailstoynov** [comment]
Yes, it does obsolete #52 and #53.

I haven't tested with previous versions. Why would someone use older versions of ansible?

**Comment by aalaesar** [comment]
thank you @egmont1227 for the feedback 👍  😃 
I have so few time available to work on this since summer.

**Pull request merged**
