### PR TITLE
Move role content to collection's  role folder

### PR DESCRIPTION
**Pull request by aalaesar**
in preparation of 2.0 when the repo become a collection. we need to move first the current role in its future folder, then create the rest of the collection structure.
I reported most of the commits done for #192  that only move the code and fix the CI but I expect the CI to temporary brake as the rest of the collection is not set

### CODE REVIEW

**Comment by wiktor2200** [comment]
There is a problem with `ansible-lint` gitbub action.  I think changing this line: https://github.com/aalaesar/install_nextcloud/pull/197/files#diff-560835e85dd8864478d2a44873857b66b14927187638ea69242607995c7a544aR16
to would help:
```
- role: aalaesar.nextcloud.install_nextcloud
```

**Comment by aalaesar** [comment]
> There is a problem with `ansible-lint` gitbub action. I think changing this line: https://github.com/aalaesar/install_nextcloud/pull/197/files#diff-560835e85dd8864478d2a44873857b66b14927187638ea69242607995c7a544aR16 would help:
> 
> ```
>     - role: aalaesar.nextcloud.install_nextcloud
> ```
Thank you @wiktor2200 . this fixed a part of the ci,
**as expected**, molecule can't work yet with the new role location as the metadata's are not yet created for it to properly use the collection.
As you can recall, in #192 the CI was working fine with the full collection setup.
The collection will be completed in the next PR after this one is merged into 2.0-dev

**Comment by aalaesar** [comment]
@staticdev @wiktor2200  I suggest we go on with this one so I can open the next one that will contain the collection's metadata's, readme, etc

**Comment by aalaesar** [comment]
@wiktor2200  @staticdev 
I need to continue on the collection conversion
I'll merge this one this week if nobody oppose it

**Review by wiktor2200 — APPROVED** [review]
I've taken one more look and LGTM.
All issues were resolved, so I think it's good to merge now.

**Comment by staticdev** [comment]
@aalaesar LGTM then if you are ok with CI break.

**Pull request merged**
