### PR TITLE
Multiple changes and gitlab-ci testing

### PR DESCRIPTION
**Pull request by hispanico**
Link to testing pipelines:
https://gitlab.ninux.org/hispanico/ansible-nextcloud/pipelines?scope=branches

Changes:
- Replaced all 'include' for task with 'include_tasks' to fix DEPRECATION WARNING in ansible 2.4
- Configured NC config.php manipolation tasks with occ command
- Added redis server installation
- Added copy of file mimetypemapping.json to set custom mimetypemapping (es. ownpad app file extension)
- Disebled apache mod_ssl when tls is false
- Added nextcloud settings:
   - trusted proxies list
   - redis
   - backgroud jobs with cron
   - custom settings

- Added mysql settings for utf8mb4:
   - innodb_large_prefix=on
   - innodb_file_format=barracuda
   - innodb_file_per_table=true

- Created .gitlab-ci.yml for testing
   - Ubuntu Xenial
   - Ubuntu Trusty
   - Debian Stretch
   - Debian Jessie

- Created testing playbooks
   - nextcloud10_mariadb.yml
   - nextcloud10_mysql.yml
   - nextcloud10_nginx.yml
   - nextcloud10_psql.yml
   - nextcloud_mariadb.yml
   - nextcloud_mysql.yml
   - nextcloud_nginx.yml
   - nextcloud_psql.yml

- Update README.md

- Set just ansible syntax-check in travis

### CODE REVIEW

**Comment by aalaesar** [comment]
Hi @hispanico 
Thank you for the PR. ☺️ 
Those are very nice additions. 👍 
Would you like to re-enable travis full-testing with nextcloud10_psql.yml (the travis testing env is ubuntu 14.04, but can't install mysql/mariadb somehow) ?


Regards,
Aal.

**Comment by hispanico** [comment]
Hi @aalaesar,
we got an error on travis with psql as well.

Regards,
Marco

**Comment by aalaesar** [comment]
Hi @ thx for the commit.
this is a environment issue:
```shell
Setting up postgresql-10 (10.1-1.pgdg14.04+1) ...
Refused to start PostgreSQL 10, because PostgreSQL 9.2 is currently running! You should first stop 9.2 instance...
```
seems postgresql is a meta package pointing to psql-10 while Travis 's trusty have PostgreSQL 9.2 preinstalled and running.
I suggest adding 
```yaml
before_install:
  - service postgresql stop
or
  - sudo apt-get remove postgresql
```
to .travis.yml
Regards,
Aal.

**Comment by aalaesar** [comment]
Hi.
Last failed at the same task, for the same reason.
In fact the apt-get purge didn't worked:
```shell
sudo apt-get purge postgresql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'postgresql' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
```
I whould say `postgresql-9.2` but i'm not sure
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=postgresql-9&searchon=names

**Comment by aalaesar** [comment]
Hi @hispanico 
nicely done !!
Thanks for the collaboration

**Pull request merged**
