### PR TITLE
 Using ipwrap on templates to add brackets when it is needed 

### PR DESCRIPTION
**Pull request by santiagomr**
According to what was discussed in #65, I send you the PR.

### CODE REVIEW

**Comment by aalaesar** [comment]
Hi @santiagomr 
:+1: 
If you could add ipwrap also to the nginx plugin it would be perfect :smile: 
(I tried to push the commit on the PR but it failed)
nginx_nc.j2:
```yaml
server_name {{ nextcloud_trusted_domain | ipaddr | join(' ') }};  # x2
```

**Comment by santiagomr** [comment]
@aalaesar, I did the rebase on the latest commit of master and added ipwrap to the nginx template.

Finally, I added `netaddr` in the `.travis.yml`, but an error occurs during the build. Maybe you know better why.

**Comment by aalaesar** [comment]
Looked over the error msg. 
Looks like an incompatibility issue between dist python packages and pypi packages and versions gap. (This is Ubuntu 16.04 after all)
It would've probably safer to install via apt python-netaddr

**Comment by santiagomr** [comment]
Ok, I change it from pip to apt

**Comment by santiagomr** [comment]
Yes, switching to apt solved the problem.

**Pull request merged**
